tasks:
  - name: create virtual environment
    init: 
      cd .. &&
      python3 -m venv reimagined-octo-env &&
      cd reimagined-octo-memory/ &&
      source ../reimagined-octo-env/bin/activate &&
      python3 -m pip install -r requirements.txt &&
      python3 -m pip install --upgrade pip
      

vscode:
  extensions:
    - eamodio.gitlens
    - ms-python.python
    - TabNine.tabnine-vscode
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
