tasks:
  - name: create virtual environment
    before: cd ..
    init: python3 -m venv reimagined-octo-env
    command: 
      cd reimagined-octo-memory/
      source ../reimagined-octo-env/bin/activate
      python3 -m pip install -r requirements.txt

vscode:
  extensions:
    - eamodio.gitlens
    - ms-python.python
    - TabNine.tabnine-vscode
